export enum Modals {
  UNSUBSCRIBE_MODAL = "UNSUBSCRIBE_MODAL",
  SUBSCRIBE_MODAL = "SUBSCRIBE_MODAL",
  NEW_FIVE_MODAL = "NEW_FIVE_MODAL",
  EDIT_FIVE_MODAL = "EDIT_FIVE_MODAL",
  REMOVE_FIVE_MODAL = "REMOVE_FIVE_MODAL",
  JOIN_GROUP_MODAL = "JOIN_GROUP_MODAL",
  NEW_GROUP_MODAL = "NEW_GROUP_MODAL",
  GROUP_INFORMARION_MODAL = "GROUP_INFORMATION_MODAL",
}
