export enum Modals {
  CONFIRM_MODAL = "CONFIRM_MODAL",
  SUBSCRIBE_MODAL = "SUBSCRIBE_MODAL",
  NEW_FIVE_MODAL = "NEW_FIVE_MODAL",
  EDIT_FIVE_MODAL = "EDIT_FIVE_MODAL",
  REMOVE_FIVE_MODAL = "REMOVE_FIVE_MODAL",
}
